# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180322_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pub',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='pub_time',
            field=models.DateField(),
        ),
    ]
