# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180328_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='group',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='read',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
