# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180328_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='', max_length=150),
        ),
    ]
