# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to='banner/'),
        ),
    ]
