# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180329_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(blank=True, upload_to='banner/')),
                ('site_title', models.CharField(max_length=150)),
                ('site_keywords', models.CharField(default='', max_length=150)),
                ('site_description', models.TextField(default='')),
                ('page_title', models.CharField(max_length=150)),
                ('page_subtitle', models.CharField(max_length=150)),
            ],
        ),
    ]
